name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  GOFLAGS: '-mod=readonly'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run checks
        env:
          LINTER_FLAGS: '--timeout=2m'
        run: make check-circle
